---
- hosts: servers
  remote_user: root
  tasks:
    - name: Download .war
      get_url:
        url: http://192.168.0.31:8081/artifactory/libs-release-local/com/mkyong/CounterWebApp/webapp-1.0.war
        dest: /apache-tomcat-8.5.24/webapps/deploy-tomcat-ansible.war
    - name: stop tomcat
      shell: /apache-tomcat-8.5.24/bin/shutdown.sh
    - name: start tomcat
      shell: /apache-tomcat-8.5.24/bin/startup.sh
